# Dependencies
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yale Data Science
tagline:          'An Undergraduate Organization'
description:      'An Undergraduate Organization'
url:              http://yaledatascience.github.io/

author:
  name:           'Yale Data Science'
  url:            https://github.com/YaleDataScience

paginate:         5

# Custom vars
version:          4.0.0

github:
  repo:           https://github.com/YaleDataScience/